create table hibernate_sequences (
    sequence_name varchar(50),
    next_val bigint
);

create table ACCOUNT (
    TYPE varchar(25) not null,
    ID bigint generated by default as identity,
    VERSION bigint,
    CREDIT_LIMIT double,
    DEPOSITOR_ID bigint not null,
    primary key (ID)
);

create table ACCOUNT_ENTRY (
    ID bigint generated by default as identity,
    AMOUNT double not null,
    DATE date not null,
    DETAILS varchar(50) not null,
    REFERENCE varchar(50) not null,
    TYPE varchar(50) not null,
    ACCOUNT_ID bigint,
    primary key (ID)
);

create table ADDRESS (
    ID bigint generated by default as identity,
    CITY varchar(25) not null,
    COUNTRY varchar(50) not null,
    STREET varchar(50) not null,
    ZIP_CODE varchar(6) not null,
    DEPOSITOR_ID bigint,
    primary key (ID)
);

create table CONTACT_DETAIL (
    ID bigint generated by default as identity,
    TYPE varchar(50) not null,
    VALUE varchar(50) not null,
    DEPOSITOR_ID bigint,
    primary key (ID)
);

create table CREDIT_CONDITION (
    ID bigint generated by default as identity,
    DESCRIPTION varchar(1024) not null,
    VERSION bigint,
    primary key (ID)
);

create table DEPOSITOR (
    ID bigint generated by default as identity,
    NAME varchar(255) not null,
    SURNAME varchar(255) not null,
    VERSION bigint,
    primary key (ID)
);

alter table ACCOUNT 
    add constraint FK_3rglsd6k3e87yqm10wpqoex0v 
    foreign key (DEPOSITOR_ID) 
    references DEPOSITOR;

alter table ACCOUNT_ENTRY 
    add constraint FK_fkto0jgas0ortrjcdirbnotwa 
    foreign key (ACCOUNT_ID) 
    references ACCOUNT;

alter table ADDRESS 
    add constraint FK_3mw83khhtr5rj10mxtclbh6jt 
    foreign key (DEPOSITOR_ID) 
    references DEPOSITOR;

alter table CONTACT_DETAIL 
    add constraint FK_bsh5cmmqeumnpaww9d8379ifm 
    foreign key (DEPOSITOR_ID) 
    references DEPOSITOR;
